name: p_t_v
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  get_it: ^7.6.4
  flutter_pdfview: ^1.2.7
  path: 1.8.3
  sqflite: ^2.3.0
  provider: ^6.1.1
  file_picker: ^6.1.1
  json_theme: ^4.0.0
  syncfusion_flutter_pdf: ^23.2.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/theme.json
  uses-material-design: true
